apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
spec:
  replicas: 2
  selector:
    matchLables:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: gcr.io/qwiklabs-gcp-01-4dfccbf654a2/sample-app:V1
          ports:
            - containerPort: 8080
