apiVersion: v1
kind: service
metadata:
  name: sample-app-clusterip
spec:
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
type: ClusterIP
---
apiVersion: v1
kind: service
metadata:
  name: sample-app-loadbalancer
spec:
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
